version: '2'

services: 
  rabbitmq:
    image: rabbitmq:3.6.9-management-alpine
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - sky-net

  rabbitmq-producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    image: rabbitmq-producer:1.0.1
    environment: 
      - BROKER_ADDR=amqp://guest:guest@rabbitmq:5672/
      - QUEUE=test-queue
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - sky-net

  rabbitmq-consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    image: rabbitmq-consumer:1.0.1     
    environment: 
      - BROKER_ADDR=amqp://guest:guest@rabbitmq:5672/
      - QUEUE=test-queue
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge
  