version: '2'

services:
  consul:
    image: consul:0.8.3
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    links:
      - gin-web-01
      - gin-web-02
    networks:
      - sky-net

  gin-web-01:
    image: gin-web:1.0.1
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - sky-net

  gin-web-02:
    image: gin-web:1.0.1
    environment:
      - PORT=9090
    ports:
      - "9090:9090"
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge  