apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: simple-k8s-server
  name: simple-k8s-server
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    io.kompose.service: simple-k8s-server
  type: NodePort
status:
  loadBalancer: {}
