apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: simple-k8s-server
  name: simple-k8s-server
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simple-k8s-server
    spec:
      containers:
      - env:
        - name: PORT
          value: "9090"
        image: danigilmayol/simple-k8s-server:1.0.1
        name: simple-k8s-server
        ports:
        - containerPort: 9090
        resources: {}

        readinessProbe:
          httpGet:
            path: /info
            port: 9090
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 5
                  
      restartPolicy: Always
status: {}
